- name: Configure | Create storage, log and keyfile directory
  ansible.builtin.file:
    path: "{{ item.name }}"
    recurse: "{{ item.recurse }}"
    state: directory
    owner: mongodb
    group: mongodb
  loop:
    - name: Configure | mongodb_directory.storage
      recurse: false
    - name: mongodb_directory.log
      recurse: true
    - name: mongodb_directory.keyfile
      recurse: false

- name: Configure | Getting status of keyfile
  ansible.builtin.stat:
    path: "{{ mongodb_directory.keyfile }}/keyfile"
  register: st

- name: Configure | Generate and create keyfile
  block:
    - name: Configure | Generate keyfile value 
      ansible.builtin.command: openssl rand -base64 741
      run_once: true
      register: keyfilevalue

    - name: Configure | Create keyfile
      ansible.builtin.template:
        src: templates/keyfile.j2
        dest: "{{ mongodb_directory.keyfile }}/keyfile"
        force: false
        owner: mongodb
        group: mongodb
        mode: '0400'
  when: st.stat.exists == false or st.stat.size == 0
