- name: Create the user administrator
  community.mongodb.mongodb_user:
    database: admin
    name: admin
    password: pass
    roles: root
    login_host: 127.0.0.1
    create_for_localhost_exception: /var/log/mongodb/localexception
  # no_log: true
  when: groups.mongod.index(inventory_hostname) == 0 