- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: yes

- name: Install prerequired packages 
  ansible.builtin.apt:
    pkg: "{{ required_pkg }}"
    state: present
    update_cache: true
    
- name: Install pymongo python package specifically,
  ansible.builtin.pip:
    name: pymongo=={{ pymongo_version }}
    executable: pip3
    
- name: Import the MongoDB public GPG key
  ansible.builtin.shell:
    cmd: curl -fsSL https://pgp.mongodb.com/server-7.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
    creates: /usr/share/keyrings/mongodb-server-7.0.gpg

- name: Create list file for MongoDB
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/mongodb-org-7.0.list
    content: "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse"

- name: Check mongodb-org installation
  ansible.builtin.apt:
    pkg:
      - mongodb-org={{ mongodb_org_version }}
      - mongodb-org-database={{ mongodb_org_version }}
      - mongodb-org-server={{ mongodb_org_version }}
      - mongodb-mongosh={{ mongodb_mongosh_version }}
      - mongodb-org-mongos={{ mongodb_org_version }}
      - mongodb-org-tools={{ mongodb_org_version }}
      - mongodb-org-shell={{ mongodb_org_version }}
      - mongodb-org-database-tools-extra={{ mongodb_org_version }}
    state: present
    update_cache: true
    autoremove: yes

- name: Hold mongo-org package
  ansible.builtin.dpkg_selections:
    name: "{{item}}"
    selection: hold
  loop: "{{ mongo_org_pkg }}"
    