- name: Replicaset | build member list
  set_fact:
    members: >-
      {{
        members | default([]) +
        [{
          'host': hostvars[item].ansible_host + ':{{ mongodb_net.port }}',
          'priority': member_weight[hostvars[item].mongo_replication_role]
        }]
      }}
  loop: "{{ ansible_play_hosts }}"
  run_once: true
  vars:
    member_weight:
      primary: 2
      secondary: 1
      arbiter: 0

- name: Replicaset | set fact for arbiter index number
  set_fact:
    arbiter_index: "{{ hostid }}"
  when: hostvars[item]['mongo_arbiter']
  loop: "{{ ansible_play_hosts }}"
  loop_control:
    index_var: hostid

- name: Replicaset | Template a file to /etc/mongod.conf
  ansible.builtin.template:
    src: templates/mongod.conf.j2
    dest: /etc/mongod.conf
    force: yes
    owner: mongodb
    group: mongodb
    mode: '0644'
  notify: 
  - restart mongod
- name: debug
  debug:
    msg: '{{mongodb_net.bindIp}}'

- name: Replicaset | Flush handlers
  meta: flush_handlers

- name: Replicaset | Create replica set
  community.mongodb.mongodb_replicaset:
    login_host: 127.0.0.1
    replica_set: "{{replicaSet_name}}"
    members: "{{ members }}"
    arbiter_at_index: "{{ arbiter_index | default(omit) }}"
  when: groups.mongod.index(inventory_hostname) == 0