- name: Generating Key File if not available
  ansible.builtin.shell: 
    cmd: curl -fsSL https://pgp.mongodb.com/server-7.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
    cmd: openssl rand -base64 741 
    creates: /usr/share/keyrings/mongodb-server-7.0.gpg 