- name: Create keyfile directory for MongoDB
  ansible.builtin.file:
    path: /var/lib/mongo
    state: directory
    owner: mongodb
    group: mongodb

- name: Generate keyfile value 
  ansible.builtin.command: openssl rand -base64 741
  run_once: true
  register: keyfilevalue

- name: .:(Debian):. create keyfile
  template:
    src: keyfile.j2
    dest: /var/lib/mongo/keyfile
    owner: mongodb
    group: mongodb
    mode: '400'


