- name: Create administrative user
  mongodb_user:
    database: admin
    name: admin
    password: pass
    update_password: "on_create"
    roles: root
    # login_host: "{{ mongodb_net_bindip.split(',') | map('replace', '0.0.0.0', '127.0.0.1') | list  | first }}"
    # login_user: admin
    # login_password: pass #causes bug when uncommented
  # no_log: true
  
 