# - name: Template file template file to /etc/file.conf 
#   ansible.builtin.template:
#     src: mongod.conf.j2
#     dest: /etc/mongod.conf
#     force: yes
#     owner: mongodb
#     group: mongodb
#     mode: '0644'
#   notify: 
#   - daemon reload
#   - restart mongod

# - name: Flush handlers
#   meta: flush_handlers

- name: Create the user administrator
  community.mongodb.mongodb_user:
    database: admin
    name: admin
    password: pass
    roles: root
    login_host: 127.0.0.1
  # no_log: true
  when: groups.mongod.index(inventory_hostname) == 0
