- name: Create administrative user
  mongodb_user:
    database: admin
    name: admin
    password: pass
    replica_set: rs0
    roles: root
    # login_host: "{{ mongodb_net_bindip.split(',') | map('replace', '0.0.0.0', '127.0.0.1') | list  | first }}"  
  # no_log: true
  
 