- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: yes

- name: Check gnupg and curl installation
  ansible.builtin.apt:
    name: [gnupg, curl]
    state: present
    update_cache: true

- name: Import the MongoDB public GPG key
  ansible.builtin.shell:
    cmd: curl -fsSL https://pgp.mongodb.com/server-7.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
    creates: /usr/share/keyrings/mongodb-server-7.0.gpg

- name: Create list file for MongoDB
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/mongodb-org-7.0.list
    content: "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse"

- name: Check mongodb-org installation
  ansible.builtin.apt:
    pkg:
      - mongodb-org=7.0.1
      - mongodb-org-database=7.0.1
      - mongodb-org-server=7.0.1
      - mongodb-mongosh=2.0.1
      - mongodb-org-mongos=7.0.1
      - mongodb-org-tools=7.0.1
      - mongodb-org-shell=7.0.1
      - mongodb-org-database-tools-extra=7.0.1
    state: present
    update_cache: true
    autoremove: yes

- name: Hold mongo-org package
  ansible.builtin.dpkg_selections:
    name: "{{item}}"
    selection: hold
  loop:
    - mongodb-org
    - mongodb-org-database
    - mongodb-org-server
    - mongodb-mongosh
    - mongodb-org-mongos
    - mongodb-org-tools
    - mongodb-org-shell
    - mongodb-org-database-tools-extra