## mongo configuration
mongodb_keyfile_directory: /var/lib/mongo-auth
# mongodb_storage_directory: /var/lib/mongodb
mongodb_storage_directory: /mnt/mongodb_data
mongodb_log_directory: /var/log/mongodb

## mongo authentication
mongodb_user_admin_name: admin
mongodb_user_admin_password: pass

## mongo replication
replicaSet_name: rs0

primary_count: 1
secondary_count: 1
arbiter_count: 1

## net Options
mongodb_net_bindip: 0.0.0.0                   
mongodb_net_port: 27017                          
