- name: Create storage directory for MongoDB
  ansible.builtin.file:
    path: /var/lib/mongodb
    state: directory
    owner: mongodb
    group: mongodb

- name: Create log directory for MongoDB
  ansible.builtin.file:
    path: /var/log/mongodb
    recurse: true
    state: directory
    owner: mongodb
    group: mongodb

- name: Create keyfile directory for MongoDB
  ansible.builtin.file:
    path: /var/lib/mongo-auth
    state: directory
    owner: mongodb
    group: mongodb

- name: Generate keyfile value 
  ansible.builtin.command: openssl rand -base64 741
  run_once: true
  register: keyfilevalue

- name: Create keyfile
  template:
    src: templates/keyfile.j2
    dest: /var/lib/mongo-auth/keyfile
    force: false
    owner: mongodb
    group: mongodb
    mode: '0400'