- name: cluster | build member list
  set_fact:
    members: >-
      {{
        members | default([]) +
        [{
          'host': item + ':27017',
          'priority': member_weight[hostvars[item].mongo_replication_role]
        }]
      }}
  loop: "{{ ansible_play_hosts }}"
  run_once: true
  vars:
    member_weight:
      primary: 2
      secondary: 1
      arbiter: 0

- name: cluster | set fact for arbiter index number
  set_fact:
    arbiter_index: "{{ hostid }}"
  when: hostvars[item]['mongo_arbiter']
  loop: "{{ ansible_play_hosts }}"
  loop_control:
    index_var: hostid

- name: Template a file to /etc/file.conf 
  ansible.builtin.template:
    src: templates/mongod_temp.conf.j2
    dest: /etc/mongod.conf
    force: yes
    owner: mongodb
    group: mongodb
    mode: '0644'
  notify: 
  - daemon reload
  - restart mongod

- name: Flush handlers
  meta: flush_handlers

- name: Create replica set
  community.mongodb.mongodb_replicaset:
    login_host: 127.0.0.1
    replica_set: "{{replicaSet_name}}"
    # members:
    # - _id: 0
    #   host: "{{ hostvars[play_hosts[0]]['ansible_host'] }}:{{ mongodb_net_port }}"
    #   priority: hostvars[play_hosts[0]]['mongo_node_priority'] | int
    
    # - _id: 1
    #   host: "{{ hostvars[play_hosts[1]]['ansible_host'] }}:{{ mongodb_net_port }}"
    #   priority: hostvars[play_hosts[1]]['mongo_node_priority'] | int
  
    # - _id: 2
    #   host: "{{ hostvars[play_hosts[2]]['ansible_host'] }}:{{ mongodb_net_port }}"
    #   priority: hostvars[play_hosts[2]]['mongo_node_priority'] | int
    members: "{{ members }}"
    arbiter_at_index: "{{ arbiter_index | default(omit) }}"
  when: groups.mongod.index(inventory_hostname) == 0