- name: Create storage directory for MongoDB
  ansible.builtin.file:
    path: "{{ mongodb_directory.storage }}"
    state: directory
    owner: mongodb
    group: mongodb

- name: Create log directory for MongoDB
  ansible.builtin.file:
    path: "{{ mongodb_directory.log }}"
    recurse: true
    state: directory
    owner: mongodb
    group: mongodb

- name: Create keyfile directory for MongoDB
  ansible.builtin.file:
    path: "{{ mongodb_directory.keyfile }}"
    state: directory
    owner: mongodb
    group: mongodb

- name: Generate keyfile value 
  ansible.builtin.command: openssl rand -base64 741
  run_once: true
  register: keyfilevalue

- name: Create keyfile
  ansible.builtin.template:
    src: templates/keyfile.j2
    dest: "{{ mongodb_directory.keyfile }}/keyfile"
    force: false
    owner: mongodb
    group: mongodb
    mode: '0400'