- name: Install MongoDB
  import_tasks: install.yaml

- name: Configuring
  import_tasks: configure.yaml

- name: Assertion 
  import_tasks: assertion.yaml

- name: Creating Replicaset
  import_tasks: replicaset.yaml

- name: Creating administrative user
  import_tasks: createuser.yaml