- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    force: yes

- name: Starting mongodb service
  ansible.builtin.service:
    name: mongod.service
    state: started
    enabled: yes

- name: cluster | build member list
  set_fact:
    members: >-
      {{
        members | default([]) +
        [{
          'host': item + ':{{ mongo_net.port }}',
          'priority': member_weight[hostvars[item].mongo_replication_role]
        }]
      }}
  loop: "{{ ansible_play_hosts }}"
  run_once: true
  vars:
    member_weight:
      primary: 3
      secondary: 2
      arbiter: 1


- name: cluster | initial build
  community.mongodb.mongodb_replicaset:
    login_host: localhost
    login_port: "{{ mongo_net.port }}"
    login_user: admin
    login_password: "{{ mongo_admin_pass }}"
    replica_set: "{{ mongo_replication.replSetName }}"
    members: "{{ members }}"
    arbiter_at_index: 2
  when: mongo_primary
