- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    force: yes

- name: Starting mongodb service
  ansible.builtin.service:
    name: mongod.service
    state: started
    enabled: yes
 
      
- name: Create replica set
  community.mongodb.mongodb_replicaset:
    login_host: 172.16.21.11
    login_user: admin
    login_password: pass
    replica_set: test_replicaset
    members:
      - "172.16.21.11:27017"
      - "172.16.21.12:27017"
      - "172.16.21.13:27017"
  when: groups.mongod.index(inventory_hostname) == 0