- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    force: yes

- name: Restarting mongodb
  systemd:
    name: mongod
    enabled: yes
    daemon_reload: yes


- name: Create replica set 
  community.mongodb.mongodb_replicaset:
    login_user: admin
    login_password: pass
    replica_set: test_replicaset
    members:
    - "172.16.21.11:27017"
    - "172.16.21.12:27017"
    - "172.16.21.13:27017"
  when: inventory_hostname == "{{ groups['all'] | first }}"