# - name: Installing pre-required packages
#   import_tasks: prerequirment.yaml
  
# - name: cluster | build member list
#   set_fact:
#     members: >-
#       {{
#         members | default([]) +
#         [{
#           'host': item + ':27017',
#           'priority': member_weight[hostvars[item].mongo_replication_role]
#         }]
#       }}
#   loop: "{{ ansible_play_hosts }}"
#   run_once: true
#   vars:
#     member_weight:
#       primary: 3
#       secondary: 2
#       arbiter: 1

- name: Template a file to /etc/file.conf 
  ansible.builtin.template:
    src: mongod_temp.conf.j2
    dest: /etc/mongod.conf
    force: yes
    owner: mongodb
    group: mongodb
    mode: '0644'
  notify: 
  - daemon reload
  - restart mongod

- name: Flush handlers
  meta: flush_handlers

- name: Create replica set
  community.mongodb.mongodb_replicaset:
    login_host: 172.16.21.11
    replica_set: rs0
    members:
    - _id: 0
      host: "172.16.21.11:27017"
      priority: 1
    - _id: 1
      host: "172.16.21.12:27017"
      priority: 0.5
    - _id: 2
      host: "172.16.21.13:27017"
      priority: 0.5
    # arbiter_at_index: 2
  when: groups.mongod.index(inventory_hostname) == 0