- hosts: all
  become: true
  become_user: root

  tasks:
    # - name: Install MongoDB
    #   include_role:
    #     name: install
    - name: assserting
      include_role:
        name: assert

    - name: Starting MongoDB service
      include_role:
        name: service

    - name: Creating administrative user
      include_role:
        name: create-user

    - name: Configuring
      include_role:
        name: configure

    - name: Creating Replicaset
      include_role:
        name: replicaset
